SELECT * FROM DEPT;
SELECT * FROM EMP;

/*DEPT 테이블의 LOC별 최대 월급을 받는 사원을 검색*/

SELECT E.DEPTNO, E.ENAME, D.MAX_SAL
FROM 
(
SELECT DEPTNO, MAX(SAL) MAX_SAL FROM EMP GROUP BY DEPTNO
) D JOIN EMP E
ON D.DEPTNO = E.DEPTNO
ORDER BY E.DEPTNO;


/*employees 테이블에서 직원의 모든 정보, 부서이름, 지역 이름, 나라 이름 출력*/

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;

SELECT D.*, L.STREET_ADDRESS, L.COUNTRY_ID
FROM (SELECT E.*, D.DEPARTMENT_NAME, D.LOCATION_ID  
FROM DEPARTMENTS D JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID) D JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID;


/*PLAYER 테이블에서 팀별 최대 키를 가진 선수 조회*/

SELECT * FROM PLAYER;
SELECT * FROM TEAM;

SELECT P.*
FROM
(
SELECT TEAM_ID, MAX(HEIGHT) "MAX_HEIGHT"
FROM PLAYER GROUP BY TEAM_ID
) T JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID AND T.MAX_HEIGHT = P.HEIGHT
ORDER BY P.TEAM_ID;


/* TEAM테이블에서 울산현대와 삼성블루윙즈의 경기날짜 경기장이름 출력 */
SELECT * FROM TEAM;
SELECT * FROM SCHEDULE;
SELECT * FROM STADIUM;

SELECT T.*, S.STADIUM_NAME 
FROM 
TEAM T JOIN STADIUM S 
ON T.STADIUM_ID =S.STADIUM_ID AND (T.TEAM_NAME = '울산현대' OR T.TEAM_NAME= '삼성블루윙즈');



/*MOD 함수를 사용하여 사원번호가 짝수인 사람만 출력하시오.*/
SELECT * FROM EMP
WHERE MOD(EMPNO,2)=0;




